import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/modules/user/common/nav-bar/views";
import Footer from "@/modules/user/common/footer/views";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
